<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
$APPLICATION->SetTitle(""); ?><?$APPLICATION->IncludeComponent(
	"nextype:forms",
	"popup",
	Array(
		"CAPTHCA" => "N",
		"DECODE_FIELDNAME" => "Y",
		"FIELDS" => "W3sibGFiZWwiOiJcdTA0MWFcdTA0MzBcdTA0M2EgXHUwNDMyXHUwNDMwXHUwNDQxIFx1MDQzN1x1MDQzZVx1MDQzMlx1MDQ0M1x1MDQ0Mj8iLCJuYW1lIjoiTkFNRSIsInR5cGUiOiJ0ZXh0IiwicmVxdWlyZWQiOiJZIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIifSx7ImxhYmVsIjoiXHUwNDFhXHUwNDNlXHUwNDNkXHUwNDQyXHUwNDMwXHUwNDNhXHUwNDQyXHUwNDNkXHUwNDRiXHUwNDM5IFx1MDQ0Mlx1MDQzNVx1MDQzYlx1MDQzNVx1MDQ0NFx1MDQzZVx1MDQzZCIsIm5hbWUiOiJQSE9ORSIsInR5cGUiOiJ0ZXh0IiwicmVxdWlyZWQiOiJZIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIrNyAoIyMjKSAjIyMtIyMtIyMifSx7ImxhYmVsIjoiXHUwNDEyXHUwNDMwXHUwNDQ4XHUwNDMwIFx1MDQzZlx1MDQzZVx1MDQ0N1x1MDQ0Mlx1MDQzMCIsIm5hbWUiOiJFTUFJTCIsInR5cGUiOiJlbWFpbCIsInJlcXVpcmVkIjoiTiIsImRlZmF1bHQiOiIiLCJ2YWx1ZXMiOiIiLCJtYXNrIjoiIn0seyJsYWJlbCI6Ilx1MDQxYVx1MDQzZVx1MDQzY1x1MDQzY1x1MDQzNVx1MDQzZFx1MDQ0Mlx1MDQzMFx1MDQ0MFx1MDQzOFx1MDQzOSIsIm5hbWUiOiJDT01NRU5UIiwidHlwZSI6InRleHRhcmVhIiwicmVxdWlyZWQiOiJOIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIifSx7ImxhYmVsIjoiXHUwNDIyXHUwNDNlXHUwNDMyXHUwNDMwXHUwNDQwIiwibmFtZSI6IlBST0RVQ1QiLCJ0eXBlIjoiaGlkZGVuIiwicmVxdWlyZWQiOiJOIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIifV0=",
		"FORM_TYPE" => "ORDER",
		"MESSAGE_ERRORALL" => "",
		"MESSAGE_SUCCESS" => "Ваш заказ успешно отправлен. Наш менеджер свяжется с Вами в ближайшее время!",
		"NAME" => "Оформление заказа",
		"PERSONAL_PROCESSING" => "Y",
		"PERSONAL_PROCESSING_PAGE" => "",
		"SEND_EMAIL_ADDRESS" => "",
		"SEND_EMAIL_ENABLED" => "Y",
		"SEND_EMAIL_EVENT_NAME" => "",
		"SEND_IBLOCK_ENABLED" => "Y",
		"SEND_IBLOCK_ID" => "10",
		"SEND_IBLOCK_TYPE" => "nt_premium_forms"
	)
);?>